version: "3.4"

services:
  slave:
    container_name: slave
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 9999
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mysql-learner

  master:
    container_name: master
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 9999
    networks:
      - mysql-learner

networks:
  mysql-learner:
    external: false
